export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_TOKEN_REQUEST = "LOGIN_TOKEN_REQUEST";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_REQUESTED = "LOGOUT_REQUESTED";
export const LOGOUT_REQUEST_SUCCESS = "LOGOUT_REQUEST_SUCCESS";
export const LOGOUT_REQUEST_FAIL = "LOGOUT_REQUEST_FAIL";
